""" Problem 2

Even Fibonacci numbers
----------------------

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


def genfib(a=1, b=2, limit=None):
	b, c = b - a, a
	while limit is None or c < limit:
		yield c
		b, c = c, b + c


def answer():
	return sum(f for f in genfib(limit=4000000) if f % 2 == 0)


if __name__ == '__main__':
	print(answer())
